from __future__ import annotations


def runtime_helpers_source() -> list[str]:
    return [
        "def _to_serializable(value):",
        "    if hasattr(value, 'detach'):",
        "        value = value.detach()",
        "    if hasattr(value, 'cpu'):",
        "        value = value.cpu()",
        "    if hasattr(value, 'numpy'):",
        "        value = value.numpy()",
        "    if hasattr(value, 'tolist'):",
        "        return value.tolist()",
        "    return value",
        "",
        "",
        "def _count_contacts(contact_data):",
        "    valid_mask = contact_data.get('valid_mask')",
        "    if valid_mask is not None:",
        "        mask = _to_serializable(valid_mask)",
        "        if isinstance(mask, list):",
        "            stack = [mask]",
        "            count = 0",
        "            while stack:",
        "                current = stack.pop()",
        "                if isinstance(current, list):",
        "                    stack.extend(current)",
        "                else:",
        "                    count += int(bool(current))",
        "            return count",
        "        return int(bool(mask))",
        "",
        "    geom_a = _to_serializable(contact_data.get('geom_a', []))",
        "    if isinstance(geom_a, list):",
        "        if geom_a and isinstance(geom_a[0], list):",
        "            return len(geom_a[0])",
        "        return len(geom_a)",
        "    return 0",
        "",
        "",
        "def _is_floating_base_entity(entity):",
        "    try:",
        "        return int(entity.n_qs) >= 7 and int(entity.n_dofs) >= 6",
        "    except Exception:",
        "        return False",
        "",
        "",
        "def _as_float_vector(value):",
        "    data = _to_serializable(value)",
        "    if isinstance(data, list) and data and isinstance(data[0], list):",
        "        data = data[0]",
        "    if not isinstance(data, list):",
        "        return None",
        "    output = []",
        "    for component in data:",
        "        if not isinstance(component, (int, float)) or isinstance(component, bool):",
        "            return None",
        "        output.append(float(component))",
        "    return output",
        "",
        "",
        "def _get_floating_base_root_state(entity):",
        "    if not _is_floating_base_entity(entity):",
        "        return None",
        "    qpos = _as_float_vector(entity.get_qpos())",
        "    dofs_velocity = _as_float_vector(entity.get_dofs_velocity())",
        "    if qpos is None or dofs_velocity is None:",
        "        return None",
        "    if len(qpos) < 7 or len(dofs_velocity) < 6:",
        "        return None",
        "    return {",
        "        'pos': qpos[:3],",
        "        'quat': qpos[3:7],",
        "        'vel': dofs_velocity[:3],",
        "        'ang': dofs_velocity[3:6],",
        "    }",
        "",
        "",
        "def _get_entity_root_pos(entity, envs_idx=None):",
        "    if not _is_floating_base_entity(entity):",
        "        return entity.get_pos(envs_idx)",
        "    qpos = entity.get_qpos(envs_idx=envs_idx)",
        "    return qpos[..., :3]",
        "",
        "",
        "class _FollowRootPositionProxy:",
        "    def __init__(self, entity):",
        "        self._entity = entity",
        "",
        "    def get_pos(self, envs_idx=None):",
        "        return _get_entity_root_pos(self._entity, envs_idx=envs_idx)",
        "",
        "",
        "def _follow_entity_target(entity):",
        "    if _is_floating_base_entity(entity):",
        "        return _FollowRootPositionProxy(entity)",
        "    return entity",
        "",
        "",
        "def _resolve_dofs_idx_local(entity, *, dofs_idx_local, joint_names, values_length=None):",
        "    if dofs_idx_local is not None:",
        "        if values_length is not None and len(dofs_idx_local) != values_length:",
        "            raise ValueError(",
        "                f'Length mismatch: selected {len(dofs_idx_local)} dofs by `dofs_idx_local`, '",
        "                f'but received {values_length} values.'",
        "            )",
        "        return dofs_idx_local",
        "    if joint_names is None:",
        "        if values_length is None:",
        "            return None",
        "        expected = int(entity.n_dofs)",
        "        if values_length != expected:",
        "            raise ValueError(",
        "                'Length mismatch without DoF selector: '",
        "                f'entity has {expected} DoFs but received {values_length} values. '",
        "                'Provide `dofs_idx_local` or `joint_names`, or pass full-length values.'",
        "            )",
        "        return tuple(range(expected))",
        "",
        "    resolved = []",
        "    for joint_name in joint_names:",
        "        joint = entity.get_joint(name=joint_name)",
        "        joint_dofs = tuple(int(index) for index in joint.dofs_idx_local)",
        "        if len(joint_dofs) == 0:",
        "            raise ValueError(f'Joint `{joint_name}` has no DoFs.')",
        "        resolved.extend(joint_dofs)",
        "",
        "    if values_length is not None and len(resolved) != values_length:",
        "        raise ValueError(",
        "            'Length mismatch for joint selector: '",
        "            f'resolved {len(resolved)} dofs from `joint_names`, but received {values_length} values.'",
        "        )",
        "    return tuple(resolved)",
        "",
        "",
        "def _resolve_links_idx(entity, *, links_idx_local, link_names):",
        "    if links_idx_local is not None:",
        "        return tuple(int(entity.link_start + idx) for idx in links_idx_local)",
        "    if link_names is None:",
        "        return None",
        "",
        "    resolved = []",
        "    for link_name in link_names:",
        "        link = entity.get_link(name=link_name)",
        "        resolved.append(int(link.idx))",
        "    return tuple(resolved)",
        "",
        "",
        "def _to_scalar_or_tuple(value, *, expected_size, field_name):",
        "    if isinstance(value, tuple):",
        "        if len(value) != expected_size:",
        "            raise ValueError(",
        "                f'Length mismatch: `{field_name}` expects {expected_size} values, but got {len(value)}.'",
        "            )",
        "        return tuple(float(component) for component in value)",
        "    return float(value)",
    ]
